ERROR 2025-07-19 22:12:24,670 log Internal Server Error: /api/submit-order/
Traceback (most recent call last):
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/metasoft/hanger_app/orders/views.py", line 286, in create
    Transaction.objects.create(
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/django/db/models/base.py", line 1012, in save_base
    post_save.send(
  File "/root/metasoft/hangervenv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/metasoft/hanger_app/accounts/models.py", line 48, in update_wallet_balance
    wallet.balance -= instance.amount  # خصم المبلغ من الرصيد
TypeError: unsupported operand type(s) for -=: 'decimal.Decimal' and 'float'
